### ISSUE TITLE
Global Redirect 1.6 Updates

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/globalredirect#19]
This module was ported from Global Redirect 1.5, but a 1.6 version was released with several fixes:

From https://www.drupal.org/project/globalredirect/releases/7.x-1.6

- [x] [#2596939: Add README.txt](https://www.drupal.org/project/globalredirect/issues/2596939) - N/A
- [x] [#1411704: Conflict with Domain Access as domain_url_outbound_alter() returns alias](https://www.drupal.org/project/globalredirect/issues/1411704) - Fixed in https://github.com/backdrop-contrib/globalredirect/pull/20
- [x] [#2385415: Use of undefined constant LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX](https://www.drupal.org/project/globalredirect/issues/2385415) - N/A
- [x] [#2013785: Redirect loop occurs when visiting a directory with deslash enabled.](https://www.drupal.org/project/globalredirect/issues/2013785) - Fixed in https://github.com/backdrop-contrib/globalredirect/pull/20
- [x] [#2228557: Term path options are ignored](https://www.drupal.org/project/globalredirect/issues/2228557)
- [x] [#1669088: Link to site information settings](https://www.drupal.org/project/globalredirect/issues/1669088)
- [x] [#1908466: Wrong taxonomy/term/* preg_match pattern may break CKEditor Link](https://www.drupal.org/project/globalredirect/issues/1908466)
- [x] [#1477200: The destination parameter gets blown away](https://www.drupal.org/project/globalredirect/issues/1477200)
- [x] [#1399024: d7 version uses incorrect variable name for maintenance mode](https://www.drupal.org/project/globalredirect/issues/1399024) - N/A
- [x] [#1399506: Language Path Checking should only redirect when viewing the node](https://www.drupal.org/project/globalredirect/issues/1399506)
- [x] [#1680978: Request to redirect URLs for comments to the parent node](https://www.drupal.org/project/globalredirect/issues/1680978)

**Comment by quicksketch** [comment]
I'll try to put all these in https://github.com/backdrop-contrib/globalredirect/pull/20.

**Comment by quicksketch** [comment]
All 1.6 commits have been merged in https://github.com/backdrop-contrib/globalredirect/pull/20.
