### ISSUE TITLE
Drupal Global Redirect 1.7 cross-ports

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/globalredirect#21]
There isn't a 1.7 version of Global Redirect for Drupal (yet), but there are several commits that were made to the branch that we could cross-port and get out in the Backdrop version:

https://git.drupalcode.org/project/globalredirect/-/commits/7.x-1.x

- [ ] Issue [#2385415](https://www.drupal.org/i/2385415) by PascalAnimateur, mkhamash, Koen.Pasman: Use of undefined constant LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX
- [ ] Issue [#1411704](https://www.drupal.org/i/1411704) by rimen, apemantus, rudiedirkx, maijs, BBC, BarisW, pwiniacki, nizer: Conflict with Domain Access as domain_url_outbound_alter() returns alias
- [ ] Issue [#782476](https://www.drupal.org/i/782476) by malcomio, BarisW: Pathauto and Global Redirect defaults expose usernames and more
- [ ] Issue [#2986833](https://www.drupal.org/i/2986833) by th_tushar: Add module specific permission
